version: "3"

tasks:
  inject-secrets:
    cmds:
      - '{{ if .CI | eq "true" | not}}op inject -i karakeep/karakeep.env.tpl -o karakeep.env{{end}}'
      - '{{ if .CI | eq "true" | not}}op inject -i caddy/caddy.env.tpl -o caddy.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#NEXTAUTH_SECRET=\".*\"#NEXTAUTH_SECRET=\"$NEXTAUTH_SECRET\"#" karakeep/karakeep.env.tpl > karakeep.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#MEILI_MASTER_KEY=\".*\"#MEILI_MASTER_KEY=\"$MEILI_MASTER_KEY\"#" karakeep/karakeep.env.tpl > karakeep.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#OPENAI_API_KEY=\".*\"#OPENAI_API_KEY=\"$OPENAI_API_KEY\"#" karakeep/karakeep.env.tpl > karakeep.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#NAMECHEAP_API_KEY=\".*\"#NAMECHEAP_API_KEY=\"$NAMECHEAP_API_KEY\"#" caddy/caddy.env.tpl > caddy.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#NAMECHEAP_API_USER=\".*\"#NAMECHEAP_API_USER=\"$NAMECHEAP_API_USER\"#" caddy/caddy.env.tpl > caddy.env{{end}}'
  cleanup-secrets:
    cmds:
      - defer: rm karakeep.env caddy.env
  run-playbook:
    deps:
      - inject-secrets
    cmds:
      - uv run ansible-playbook playbook.yaml --check
      - defer:
          task: cleanup-secrets
  install-ansible-deps:
    cmds:
      - uv run ansible-galaxy install -r requirements.yml
