version: "3"

tasks:
  inject-secrets:
    cmds:
      - '{{ if .CI | eq "true" | not}}op inject -i hoarder.env.tpl -o hoarder.env{{end}}'
      - '{{ if .CI | eq "true" | not}}op inject -i caddy.env.tpl -o caddy.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#NEXTAUTH_SECRET=\".*\"#NEXTAUTH_SECRET=\"$NEXTAUTH_SECRET\"#" hoarder.env.tpl > hoarder.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#MEILI_MASTER_KEY=\".*\"#MEILI_MASTER_KEY=\"#$MEILI_MASTER_KEY\"#" hoarder.env.tpl > hoarder.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#OPENAI_API_KEY=\".*\"#OPENAI_API_KEY=\"$OPENAI_API_KEY\"#" hoarder.env.tpl > hoarder.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#NAMECHEAP_API_KEY=\".*\"#NAMECHEAP_API_KEY=\"#$NAMECHEAP_API_KEY\"#" caddy.env.tpl > caddy.env{{end}}'
      - '{{ if .CI | eq "true"}}sed "s#NAMECHEAP_API_USER=\".*\"#NAMECHEAP_API_USER=\"$NAMECHEAP_API_USER\"#" caddy.env.tpl > caddy.env{{end}}'
  cleanup-secrets:
    cmds:
      - defer: rm hoarder.env caddy.env
  run-playbook:
    deps:
      - inject-secrets
    cmds:
      - uv run ansible-playbook playbook.yaml --check
      - defer:
          task: cleanup-secrets
